spring:
  application:
    name: Journal App

  datasource:
    url: jdbc:postgresql://localhost:5432/Journal_project?currentSchema=public
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect